In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
b=np.array([[4,5],[6,7]])
print(b)

[[4 5]
 [6 7]]


In [7]:
c=np.array([[[4,5],[6,7]],[[4,5],[6,7]]])
print(c)

[[[4 5]
  [6 7]]

 [[4 5]
  [6 7]]]


In [9]:
d=c.dtype
print(d)

int64


In [14]:
boolean_array=np.array([True,False])
arr_type=boolean_array.dtype
print(arr_type)

bool


In [13]:
e=np.array([2.35,6.75])
arr_type=e.dtype
print(arr_type)


float64


In [15]:
boolean_array=np.array([True,False])
print(boolean_array.dtype)

bool


In [16]:
x=np.array([True,False])
print(x.dtype)

bool
